---
root: true

plugins:
  - jest

env:
  browser: true
  es2021: true
  node: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
